### PR TITLE
A new function

### PR DESCRIPTION
**Pull request by Hexirp**
Hi, I fixed a badge and added `deboneBy`. What do you think about `deboneBy`?

Usecase:
```haskell
interpretM :: Monad m => Skeleton m a -> m a
interpretM = deboneBy $ \case
  Return a -> return a
  x :>>= f -> x >>= interpretM . f
```

### CODE REVIEW

**Comment by fumieval** [comment]
The type of `deboneBy` doesn't seem to match with the usecase.

**Comment by Hexirp** [comment]
Sorry, I fixed it.

**Comment by fumieval** [comment]
I guess it's worth a try.

**Comment by Hexirp** [comment]
Thanks.

**Pull request merged**
